{
	"info": {
		"_postman_id": "3bb30ba0-bb8c-44b8-8fd5-da7d8244c4af",
		"name": "Task-API",
		"schema": "https://schema.getpostman.com/json/collection/v2.1.0/collection.json",
		"_exporter_id": "12384551"
	},
	"item": [
		{
			"name": "Get Task by ID",
			"request": {
				"method": "GET",
				"header": [],
				"url": {
					"raw": "http://localhost:8080/task/68253ee5b0ce9e45da400a1b",
					"protocol": "http",
					"host": [
						"localhost"
					],
					"port": "8080",
					"path": [
						"task",
						"68253ee5b0ce9e45da400a1b"
					]
				}
			},
			"response": []
		},
		{
			"name": "Get Tasks",
			"request": {
				"method": "GET",
				"header": [],
				"url": {
					"raw": "http://localhost:8080/task",
					"protocol": "http",
					"host": [
						"localhost"
					],
					"port": "8080",
					"path": [
						"task"
					],
					"query": [
						{
							"key": "page",
							"value": "0",
							"disabled": true
						},
						{
							"key": "size",
							"value": "10",
							"disabled": true
						},
						{
							"key": "sortField",
							"value": "description",
							"disabled": true
						},
						{
							"key": "isCompleted",
							"value": "false",
							"disabled": true
						},
						{
							"key": "isCompleted",
							"value": "true",
							"disabled": true
						}
					]
				}
			},
			"response": []
		},
		{
			"name": "Get Event by ID",
			"request": {
				"method": "GET",
				"header": [],
				"url": {
					"raw": "http://localhost:8080/event/person/682688edfeef93394b5a7924",
					"protocol": "http",
					"host": [
						"localhost"
					],
					"port": "8080",
					"path": [
						"event",
						"person",
						"682688edfeef93394b5a7924"
					],
					"query": [
						{
							"key": "page",
							"value": "0",
							"disabled": true
						},
						{
							"key": "size",
							"value": "10",
							"disabled": true
						},
						{
							"key": "sortField",
							"value": "description",
							"disabled": true
						},
						{
							"key": "isCompleted",
							"value": "true",
							"disabled": true
						}
					]
				}
			},
			"response": []
		},
		{
			"name": "Get Event - by person email",
			"request": {
				"method": "GET",
				"header": [],
				"url": {
					"raw": "http://localhost:8080/event?email=angelo@zero.com",
					"protocol": "http",
					"host": [
						"localhost"
					],
					"port": "8080",
					"path": [
						"event"
					],
					"query": [
						{
							"key": "email",
							"value": "angelo@zero.com"
						}
					]
				}
			},
			"response": []
		},
		{
			"name": "Get Pokemon by name",
			"request": {
				"method": "GET",
				"header": [],
				"url": {
					"raw": "http://localhost:8080/pokemon/mewtwo",
					"protocol": "http",
					"host": [
						"localhost"
					],
					"port": "8080",
					"path": [
						"pokemon",
						"mewtwo"
					]
				}
			},
			"response": []
		},
		{
			"name": "Save Task",
			"request": {
				"method": "POST",
				"header": [],
				"body": {
					"mode": "raw",
					"raw": "{\n    \"description\": \"false\"\n}",
					"options": {
						"raw": {
							"language": "json"
						}
					}
				},
				"url": {
					"raw": "http://localhost:8080/task",
					"protocol": "http",
					"host": [
						"localhost"
					],
					"port": "8080",
					"path": [
						"task"
					]
				}
			},
			"response": []
		},
		{
			"name": "Save Event",
			"request": {
				"method": "POST",
				"header": [],
				"body": {
					"mode": "raw",
					"raw": "{\n    \"taskId\": \"68253ee5b0ce9e45da400a1b\",\n    \"email\": \"angelo@zero.com\",\n    \"message\": \"Publish Test\"\n}",
					"options": {
						"raw": {
							"language": "json"
						}
					}
				},
				"url": {
					"raw": "http://localhost:8080/event",
					"protocol": "http",
					"host": [
						"localhost"
					],
					"port": "8080",
					"path": [
						"event"
					]
				}
			},
			"response": []
		},
		{
			"name": "Update Task",
			"request": {
				"method": "PUT",
				"header": [],
				"body": {
					"mode": "raw",
					"raw": "{\n    \"description\": \"true\",\n    \"completed\": \"true\",\n     \"statusCode\": 1\n    \n}",
					"options": {
						"raw": {
							"language": "json"
						}
					}
				},
				"url": {
					"raw": "http://localhost:8080/task/68253ee5b0ce9e45da400a1b",
					"protocol": "http",
					"host": [
						"localhost"
					],
					"port": "8080",
					"path": [
						"task",
						"68253ee5b0ce9e45da400a1b"
					]
				}
			},
			"response": []
		},
		{
			"name": "Update Event Read Status - by event id",
			"request": {
				"method": "PUT",
				"header": [],
				"body": {
					"mode": "raw",
					"raw": "{\n    \"description\": \"true\",\n    \"completed\": \"true\",\n     \"statusCode\": 1\n    \n}",
					"options": {
						"raw": {
							"language": "json"
						}
					}
				},
				"url": {
					"raw": "http://localhost:8080/event?eventId=1&isRead=false",
					"protocol": "http",
					"host": [
						"localhost"
					],
					"port": "8080",
					"path": [
						"event"
					],
					"query": [
						{
							"key": "eventId",
							"value": "1"
						},
						{
							"key": "isRead",
							"value": "false"
						}
					]
				}
			},
			"response": []
		},
		{
			"name": "Update Event Read Status - by event person email",
			"request": {
				"method": "PUT",
				"header": [],
				"body": {
					"mode": "raw",
					"raw": "{\n    \"description\": \"true\",\n    \"completed\": \"true\",\n     \"statusCode\": 1\n    \n}",
					"options": {
						"raw": {
							"language": "json"
						}
					}
				},
				"url": {
					"raw": "http://localhost:8080/event?eventPersonEmail=angelo@zero.com&isRead=true",
					"protocol": "http",
					"host": [
						"localhost"
					],
					"port": "8080",
					"path": [
						"event"
					],
					"query": [
						{
							"key": "eventPersonEmail",
							"value": "angelo@zero.com"
						},
						{
							"key": "isRead",
							"value": "true"
						}
					]
				}
			},
			"response": []
		},
		{
			"name": "Delete Task",
			"request": {
				"method": "DELETE",
				"header": [],
				"url": {
					"raw": "http://localhost:8080/task/67bfbdf0b5925f4f80dc9ab7",
					"protocol": "http",
					"host": [
						"localhost"
					],
					"port": "8080",
					"path": [
						"task",
						"67bfbdf0b5925f4f80dc9ab7"
					]
				}
			},
			"response": []
		}
	]
}